In [1]:
import sys

In [2]:
sys.path.insert(0,'../')
from unpack_ek60 import unpack_ek60_raw

In [3]:
import matplotlib.pyplot as plt
import h5py

/Users/wu-jung/miniconda3/lib/python3.6/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters


In [4]:
input_file_path = '../OOI-D20150901-T000000.raw'

In [5]:
first_ping_metadata, data_times, power_data_dict, frequencies, bin_size, \
    config_header, config_transducer = unpack_ek60_raw(input_file_path)

15:25:37  unpacking file: ../OOI-D20150901-T000000.raw


In [6]:
data_times.shape

(28717,)

In [9]:
power_data_dict['38000.0'].shape

(1046, 28717)

In [6]:
first_ping_metadata

defaultdict(list,
            {'zplsc_absorption_coeff': [0.03744031, 0.009785269, 0.05268759],
             'zplsc_bandwidth': [3026.3916, 2425.1497, 3088.4004],
             'zplsc_channel': [1, 2, 3],
             'zplsc_frequency': [120000.0, 38000.0, 200000.0],
             'zplsc_pulse_length': [0.001024, 0.001024, 0.001024],
             'zplsc_sample_interval': [0.000256, 0.000256, 0.000256],
             'zplsc_sound_velocity': [1493.8888, 1493.8888, 1493.8888],
             'zplsc_temperature': [10.0, 10.0, 10.0],
             'zplsc_timestamp': '20150901000000',
             'zplsc_transducer_depth': [0.0, 0.0, 0.0],
             'zplsc_transmit_power': [250.0, 500.0, 150.0]})

In [14]:
len(frequencies)

3

In [13]:
frequencies[1],frequencies[2],frequencies[3]

(120000.0, 38000.0, 200000.0)

In [ ]:
config_header

In [ ]:
config_transducer

In [23]:
for freq in range(1,len(frequencies)+1):
    print(str(frequencies[freq]))

120000.0
38000.0
200000.0


In [26]:
power_data_dict[str(frequencies[1])].shape

(1046, 28717)

In [27]:
for f in frequencies.keys():
    print(f)

1
2
3


In [29]:
from collections import defaultdict

In [33]:
import numpy as np

In [30]:
    sz_power_data = defaultdict(list)
    for f in frequencies.keys():
        f_str = str(frequencies[f])
        sz_power_data[f_str] = power_data_dict[f_str].shape


In [40]:
sz_power_data = np.empty(shape=(len(frequencies),2))

In [41]:
sz_power_data

array([[3.10503618e+231, 1.73060574e-077],
       [6.95032791e-310, 1.06099790e-313],
       [6.95032792e-310, 4.17211958e-309]])

In [63]:
    sz_power_data = np.empty(shape=(len(frequencies),2),dtype=int)
    for cnt,f in zip(range(len(frequencies)),frequencies.keys()):
        f_str = str(frequencies[f])
        sz_power_data[cnt,:] = power_data_dict[f_str].shape
    if np.unique(sz_power_data).shape[0]!=2:
        print('Raw file has mismatched number of pings across channels')
#         break


In [64]:
sz_power_data

array([[ 1046, 28717],
       [ 1046, 28717],
       [ 1046, 28717]])

In [69]:
sz_power_data[0,0]

1046

In [70]:
for f in frequencies.values():
    print(f)

120000.0
38000.0
200000.0


In [71]:
power_data_dict[str(f)]

array([[-168.0358843 , -134.61685119, -129.74863172, ..., -130.21899109,
        -142.93045302, -146.64629203],
       [-160.4395805 , -140.02598392, -140.10829681, ..., -140.02598392,
        -140.00246595, -140.07301986],
       [-160.34550863, -140.04950189, -140.09653783, ..., -140.06126087,
        -140.07301986, -140.07301986],
       ...,
       [-164.0143117 , -130.94804811, -147.3400721 , ..., -139.49682963,
        -130.23075008, -127.78488136],
       [-150.99711618, -131.86524888, -140.51986126, ..., -139.28516792,
        -131.24202272, -130.91277116],
       [-153.45474388, -136.92161209, -132.26505434, ..., -141.95445733,
        -136.15727812, -147.39886702]])

In [72]:
h5_file_path = '../OOI-D20150901-T000000.h5'

In [91]:
(sz_power_data[0,0],sz_power_data[0,1],None)

(1046, 28717, None)

In [93]:
tuple(sz_power_data[0,:])

(1046, 28717)

In [95]:
power_data_dict[str(f)].shape

(1046, 28717)

In [96]:
for f in frequencies.values():
    h5_file.create_dataset('power_data/%s' % str(f), sz_power_data[0,:], \
                maxshape=(sz_power_data[0,0],None), data=power_data_dict[str(f)], chunks=True)

In [103]:
for name in h5_file['power_data']:
    print(name)

120000.0
200000.0
38000.0


In [ ]:
for name in h5_file:
    print(name)

In [79]:
(sz_power_data[0,0],sz_power_data[0,1],None)

(1046, 28717, None)

In [84]:
tuple(sz_power_data[0,:])

(1046, 28717)

In [83]:
(sz_power_data[0,:])

array([ 1046, 28717])

In [104]:
first_ping_metadata

defaultdict(list,
            {'zplsc_absorption_coeff': [0.03744031, 0.009785269, 0.05268759],
             'zplsc_bandwidth': [3026.3916, 2425.1497, 3088.4004],
             'zplsc_channel': [1, 2, 3],
             'zplsc_frequency': [120000.0, 38000.0, 200000.0],
             'zplsc_pulse_length': [0.001024, 0.001024, 0.001024],
             'zplsc_sample_interval': [0.000256, 0.000256, 0.000256],
             'zplsc_sound_velocity': [1493.8888, 1493.8888, 1493.8888],
             'zplsc_temperature': [10.0, 10.0, 10.0],
             'zplsc_timestamp': '20150901000000',
             'zplsc_transducer_depth': [0.0, 0.0, 0.0],
             'zplsc_transmit_power': [250.0, 500.0, 150.0]})

In [110]:
for m,mval in first_ping_metadata.items():
#     print('%s---%s' % (m,str(mval)))
    print(mval)

20150901000000
[1, 2, 3]
[0.0, 0.0, 0.0]
[120000.0, 38000.0, 200000.0]
[250.0, 500.0, 150.0]
[0.001024, 0.001024, 0.001024]
[3026.3916, 2425.1497, 3088.4004]
[0.000256, 0.000256, 0.000256]
[1493.8888, 1493.8888, 1493.8888]
[0.03744031, 0.009785269, 0.05268759]
[10.0, 10.0, 10.0]


In [113]:
for m,mval in first_ping_metadata.items():
    h5_file.create_dataset('metadata/%s' % m, data=mval)

In [114]:
for name in h5_file['metadata']:
    print(name)

zplsc_absorption_coeff
zplsc_bandwidth
zplsc_channel
zplsc_frequency
zplsc_pulse_length
zplsc_sample_interval
zplsc_sound_velocity
zplsc_temperature
zplsc_timestamp
zplsc_transducer_depth
zplsc_transmit_power


In [171]:
type(first_ping_metadata['zplsc_timestamp'])==str

True

In [ ]:
type(first_ping_metadata['zplsc_absorption_coeff'])

In [129]:
h5_file['power_data/120000.0']

<HDF5 dataset "120000.0": shape (1046, 28717), type "<f8">

In [147]:
h5_file['metadata/zplsc_absorption_coeff']

<HDF5 dataset "zplsc_absorption_coeff": shape (3,), type "<f4">

In [188]:
h5_file['metadata/zplsc_timestamp']

<HDF5 dataset "zplsc_timestamp": shape (), type "|O">

In [162]:
h5_file['metadata/zplsc_timestamp'].astype('a')

In [212]:
dset = h5_file.create_dataset("string_ds1", (100,), dtype="S10")

In [217]:
len(first_ping_metadata['zplsc_timestamp'])

14

In [233]:
aaa = h5_file.create_dataset("test2", (100,), dtype=dt)

In [234]:
aaa[0] = '100'

In [235]:
aaa[1] = first_ping_metadata['zplsc_timestamp']

In [239]:
h5_file['test2'][1]

'20150901000000'

In [240]:
h5_file.create_dataset("test3", (1,), data=first_ping_metadata['zplsc_timestamp'], dtype=dt)

<HDF5 dataset "test3": shape (1,), type "|O">

In [247]:
dt = h5py.special_dtype(vlen=str)

In [255]:
for m,mval in first_ping_metadata.items():
    if type(first_ping_metadata[m])==str:
        h5_file.create_dataset('metadata0/%s' % m, (1,), data=mval)
    else:
        h5_file.create_dataset('metadata0/%s' % m, data=mval)

In [257]:
h5_file['metadata0/zplsc_timestamp'][0]

'20150901000000'

In [242]:
h5_file['test3'][0]

'20150901000000'

In [210]:
h5_file['string_ds']

<HDF5 dataset "string_ds": shape (100,), type "|S10">

In [193]:
for m,mval in first_ping_metadata.items():
    if type(first_ping_metadata[m])==str:
        h5_file.create_dataset('metadata6/%s' % m, (16,), data=mval, dtype="S14")
    else:
        h5_file.create_dataset('metadata6/%s' % m, data=mval)

ValueError: Shape tuple is incompatible with data

In [178]:
for m,mval in first_ping_metadata.items():
    h5_file.create_dataset('metadata3/%s' % m, data=mval)

In [180]:
h5_file['metadata4/zplsc_timestamp']

<HDF5 dataset "zplsc_timestamp": shape (), type "|O">

In [219]:
first_ping_metadata['zplsc_timestamp']

'20150901000000'

In [222]:
h5_file['metadata4/zplsc_timestamp']

'<HDF5 dataset "zplsc_timestamp": shape (), type "|O">'

In [131]:
bin_size

array([0.19121777], dtype=float32)

In [132]:
config_header

{'sounder_name': b'ER60',
 'survey_name': b'OOI',
 'transducer_count': 3,
 'transect_name': b'',
 'version': b'2.4.3'}

In [134]:
# -- header: fixed sized
for m,mval in config_header.items():
    h5_file.create_dataset('header/%s' % m, data=mval)

In [293]:
# -- header: fixed sized
for m,mval in config_header.items():
    print(len(mval))

3
0
4
5


TypeError: object of type 'int' has no len()

In [135]:
for name in h5_file['header']:
    print(name)

sounder_name
survey_name
transducer_count
transect_name
version


In [290]:
for m,mval in config_header.items():
    if type(config_header[m])==bytes:
        h5_file.create_dataset('header4/%s' % m, (1,), data=mval, dtype=h5py.special_dtype(vlen=str))
    else:
        h5_file.create_dataset('header4/%s' % m, (1,), data=mval)

TypeError: len() of unsized object

In [269]:
h5_file['header2/sounder_name'][0]

'ER60'

In [270]:
h5_file['header2/survey_name'][0]

'OOI'

In [291]:
h5_file['header4/transducer_count'][0]

3

In [292]:
range(len(config_transducer))

range(0, 3)

In [300]:
type(config_transducer[0]['angle_offset_alongship'])==float

True

In [133]:
config_transducer

[{'angle_offset_alongship': 0.0,
  'angle_offset_athwart': 0.0,
  'angle_sensitivity_alongship': 23.0,
  'angle_sensitivity_athwartship': 23.0,
  'beam_type': 1,
  'beam_width_alongship': 7.0,
  'beam_width_athwartship': 7.0,
  'channel_id': b'GPT 120 kHz 00907208a0b1 3-1 ES120-7CD',
  'dir_x': 0.0,
  'dir_y': 0.0,
  'dir_z': 0.0,
  'equiv_beam_angle': -20.700000762939453,
  'frequency': 120000.0,
  'gain': 25.0,
  'gain_table': array([23.5       , 24.79999924, 25.        , 25.        , 25.        ]),
  'gpt_software_version': b'070413',
  'pos_x': 0.0,
  'pos_y': 0.0,
  'pos_z': 0.0,
  'pulse_length_table': array([6.39999998e-05, 1.28000000e-04, 2.55999999e-04, 5.11999999e-04,
         1.02400000e-03]),
  'sa_correction_table': array([0., 0., 0., 0., 0.])},
 {'angle_offset_alongship': 0.0,
  'angle_offset_athwart': 0.0,
  'angle_sensitivity_alongship': 21.899999618530273,
  'angle_sensitivity_athwartship': 21.899999618530273,
  'beam_type': 0,
  'beam_width_alongship': 7.0999999046325

In [301]:
h5_file.close()

In [302]:
h5_file_path = '../OOI-D20150901-T000000_new.h5'

In [303]:
    # Check if input dimension makes sense, if not abort
    sz_power_data = np.empty(shape=(len(frequencies),2),dtype=int)
    for cnt,f in zip(range(len(frequencies)),frequencies.keys()):
        f_str = str(frequencies[f])
        sz_power_data[cnt,:] = power_data_dict[f_str].shape

In [304]:
    # Open new hdf5 file
    h5_file = h5py.File(h5_file_path,'x')  # create file, fail if exists

    # Store data
    # -- ping time: resizable
    h5_file.create_dataset('ping_time', (sz_power_data[0,1],), \
                    maxshape=(None,), data=data_times, chunks=True)


<HDF5 dataset "ping_time": shape (28717,), type "<f8">

In [305]:
    # -- power data: resizable
    for f in frequencies.values():
        h5_file.create_dataset('power_data/%s' % str(f), sz_power_data[0,:], \
                    maxshape=(sz_power_data[0,0],None), data=power_data_dict[str(f)], chunks=True)


In [306]:
    # -- metadata: fixed sized
    dt = h5py.special_dtype(vlen=str)
    for m,mval in first_ping_metadata.items():
        if type(first_ping_metadata[m])==str:
            h5_file.create_dataset('metadata/%s' % m, (1,), data=mval, dtype=dt)
        # when only 1 int or float object
        elif type(config_transducer[m])==int | type(config_transducer[m])==float:
            h5_file.create_dataset('header/%s' % m, (1,), data=mval)
        else:
            h5_file.create_dataset('metadata/%s' % m, data=mval)
    h5_file.create_dataset('metadata/bin_size', data=binsize)


TypeError: list indices must be integers or slices, not str

In [309]:
    for m,mval in first_ping_metadata.items():
        if type(first_ping_metadata[m])==str:
            h5_file.create_dataset('metadata2/%s' % m, (1,), data=mval, dtype=dt)
        # when only 1 int or float object
        elif type(first_ping_metadata[m])==int or type(first_ping_metadata[m])==float:
            h5_file.create_dataset('metadata2/%s' % m, (1,), data=mval)
        else:
            h5_file.create_dataset('metadata2/%s' % m, data=mval)


In [311]:
    h5_file.create_dataset('metadata/bin_size', data=bin_size)

    # -- header: fixed sized
    for m,mval in config_header.items():
        # when a string
        if type(config_header[m])==str:
            h5_file.create_dataset('header/%s' % m, (1,), data=mval, dtype=h5py.special_dtype(vlen=str))
        # when only 1 int or float object
        elif type(config_header[m])==int or type(config_header[m])==float:
            h5_file.create_dataset('header/%s' % m, (1,), data=mval)


In [326]:
for i in range(1,len(config_transducer)+1):
    print(i)

1
2
3


In [327]:
    for tx in range(len(config_transducer)):
        for m,mval in config_transducer[tx].items():
            # when a string
            if type(config_transducer[tx][m])==str:
                h5_file.create_dataset('transducer%02d2/%s' % (tx,m), (1,), data=mval, dtype=h5py.special_dtype(vlen=str))
            # when only 1 int or float object
            elif type(config_transducer[tx][m])==int or type(config_transducer[tx][m])==float:
                h5_file.create_dataset('transducer%02d2/%s' % (tx,m), (1,), data=mval)
            else:
                h5_file.create_dataset('transducer%02d2/%s' % (tx,m), data=mval)


In [321]:
    for tx in range(1,len(config_transducer)+1):
        for m,mval in config_transducer[tx].items():
            print(m)
            print(mval)


channel_id
b'GPT  38 kHz 00907208dd13 5-1 OOI.38|200'
beam_type
0
frequency
38000.0
gain
26.5
equiv_beam_angle
-20.600000381469727
beam_width_alongship
7.099999904632568
beam_width_athwartship
7.099999904632568
angle_sensitivity_alongship
21.899999618530273
angle_sensitivity_athwartship
21.899999618530273
angle_offset_alongship
0.0
angle_offset_athwart
0.0
pos_x
0.0
pos_y
0.0
pos_z
0.0
dir_x
0.0
dir_y
0.0
dir_z
0.0
pulse_length_table
[0.000256 0.000512 0.001024 0.002048 0.004096]
gain_table
[24.  26.  26.5 26.5 26.5]
sa_correction_table
[0. 0. 0. 0. 0.]
gpt_software_version
b'150120'
channel_id
b'GPT 200 kHz 00907208dd13 5-2 OOI38|200'
beam_type
0
frequency
200000.0
gain
25.0
equiv_beam_angle
-20.700000762939453
beam_width_alongship
7.0
beam_width_athwartship
7.0
angle_sensitivity_alongship
23.0
angle_sensitivity_athwartship
23.0
angle_offset_alongship
0.0
angle_offset_athwart
0.0
pos_x
0.0
pos_y
0.0
pos_z
0.0
dir_x
0.0
dir_y
0.0
dir_z
0.0
pulse_length_table
[6.39999998e-05 1.28000000e

IndexError: list index out of range