In [1]:
import os, glob

In [2]:
import xarray as xr
import numpy as np

In [3]:
import netCDF4

In [6]:
pname = '/Volumes/Transcend/Dropbox/Z_wjlee/projects/echopype/'
fname = 'test90-D20171107-T195023.nc'

In [7]:
ds = xr.open_dataset(os.path.join(pname,fname))

In [8]:
ds

<xarray.Dataset>
Dimensions:  ()
Data variables:
    *empty*
Attributes:
    Conventions:                 CF-1.7, SONAR-netCDF4, ACDD-1.3
    date_created:                2018-04-16T14:27:35.294245+02:00
    keywords:                    Simrad SU90
    license:                     None
    rights:                      Unrestricted rights
    sonar_convention_authority:  ICES
    sonar_convention_name:       SONAR-netCDF4
    sonar_convention_version:    1.0
    summary:                     Converted files from .raw format
    title:                       raw to nc converted files

In [13]:
ds.close()

In [15]:
f = netCDF4.Dataset(os.path.join(pname,fname))

In [16]:
f

<class 'netCDF4._netCDF4.Dataset'>
root group (NETCDF4 data model, file format HDF5):
    Conventions: CF-1.7, SONAR-netCDF4, ACDD-1.3
    date_created: 2018-04-16T14:27:35.294245+02:00
    keywords: Simrad SU90
    license: None
    rights: Unrestricted rights
    sonar_convention_authority: ICES
    sonar_convention_name: SONAR-netCDF4
    sonar_convention_version: 1.0
    summary: Converted files from .raw format
    title: raw to nc converted files
    dimensions(sizes): 
    variables(dimensions): 
    groups: Annotation, Environment, Platform, Provenance, Sonar, Vendor_specific

In [18]:
f['Sonar/Beam_group1']

<class 'netCDF4._netCDF4.Group'>
group /Sonar/Beam_group1:
    beam_mode: Vertical
    conversion_equation_type: 1
    dimensions(sizes): beam(64), ping_time(31)
    variables(dimensions): <class 'str'> beam(beam), float32 backscatter_i(ping_time,beam), float32 backscatter_r(ping_time,beam), float32 beam_direction_x(ping_time,beam), float32 beam_direction_y(ping_time,beam), float32 beam_direction_z(ping_time,beam), uint8 beam_stabilisation(ping_time), uint8 beam_type(ping_time), float32 beamwidth_receive_major(ping_time,beam), float32 beamwidth_receive_minor(ping_time,beam), float32 beamwidth_transmit_major(ping_time,beam), float32 beamwidth_transmit_minor(ping_time,beam), float32 equivalent_beam_angle(ping_time,beam), float32 gain_correction(ping_time,beam), int16 non_quantitative_processing(ping_time), float32 receiver_sensitivity(ping_time,beam), float32 sample_interval(ping_time), float32 sample_time_offset(ping_time), float32 time_varied_gain(ping_time), float32 transducer_gain(pi

In [9]:
ds_provenance = xr.open_dataset(os.path.join(pname,fname),group='Provenance', decode_times=False)

In [10]:
ds_provenance

<xarray.Dataset>
Dimensions:           (filenames: 0)
Dimensions without coordinates: filenames
Data variables:
    source_filenames  (filenames) object ...
Attributes:
    conversion_software_name:     P_IMR_RAW_2_NETCDF4
    conversion_software_version:  1.0.0
    conversion_time:              2018-04-12 15:50:06.205532+02:00

In [11]:
ds_sonar = xr.open_dataset(os.path.join(pname,fname),group='Sonar', decode_times=False)

In [12]:
ds_sonar

<xarray.Dataset>
Dimensions:  ()
Data variables:
    *empty*

In [13]:
ds_annotation = xr.open_dataset(os.path.join(pname,fname),group='Annotation')

ValueError: unable to decode time units 'nanoseconds since 1601-01-01 00:00:00Z' with calendar 'gregorian'. Try opening your dataset with decode_times=False.

In [95]:
ds_annotation = xr.open_dataset(os.path.join(pname,fname),group='Annotation', decode_times=False)

In [96]:
ds_annotation

<xarray.Dataset>
Dimensions:              (time: 0)
Coordinates:
  * time                 (time) uint64 
Data variables:
    annotation_text      (time) object ...
    annotation_category  (time) object ...

In [98]:
ds_annotation.time

<xarray.DataArray 'time' (time: 0)>
array([], dtype=uint64)
Coordinates:
  * time     (time) uint64 
Attributes:
    axis:           T
    calendar:       gregorian
    long_name:      Timestamps of annotations
    standard_name:  time
    units:          nanoseconds since 1601-01-01 00:00:00Z

In [ ]:
ds_annotation.annotation_category

In [174]:
ds_env = xr.open_dataset(os.path.join(pname,fname),group='Environment', decode_times=False)

In [175]:
ds_env

<xarray.Dataset>
Dimensions:                 (frequency: 1)
Coordinates:
  * frequency               (frequency) float32 30000.0
Data variables:
    absorption_indicative   (frequency) float32 ...
    sound_speed_indicative  (frequency) float32 ...

In [101]:
ds_env.absorption_indicative

<xarray.DataArray 'absorption_indicative' (frequency: 1)>
array([0.006], dtype=float32)
Coordinates:
  * frequency  (frequency) float32 30000.0
Attributes:
    long_name:  Indicative acoustic absorption
    units:      dB/m
    valid_min:  0.0

In [102]:
ds_env.sound_speed_indicative

<xarray.DataArray 'sound_speed_indicative' (frequency: 1)>
array([1490.], dtype=float32)
Coordinates:
  * frequency  (frequency) float32 30000.0
Attributes:
    long_name:      Indicative sound speed
    standard_name:  speed_of_sound_in_sea_water
    units:          m/s
    valid_min:      0.0

In [168]:
freq = np.array([30000.0], dtype='float32')

da_absorption_indicative = xr.DataArray(np.array([0.006], dtype='float32'),
                                        coords=[freq], dims=['frequency'],
                                        attrs={'long_name': "Indicative acoustic absorption", 
                                               'units': "dB/m",
                                               'valid_min': 0.0})
da_sound_speed_indicative = xr.DataArray(np.array([1490.], dtype='float32'),
                                         coords=[freq], dims=['frequency'],
                                         attrs={'long_name': "Indicative sound speed",
                                                'standard_name': "speed_of_sound_in_sea_water",
                                                'units': "m/s",
                                                'valid_min': 0.0})

In [169]:
da_absorption_indicative

<xarray.DataArray (frequency: 1)>
array([0.006], dtype=float32)
Coordinates:
  * frequency  (frequency) float32 30000.0
Attributes:
    long_name:  Indicative acoustic absorption
    units:      dB/m
    valid_min:  0.0

In [170]:
da_sound_speed_indicative

<xarray.DataArray (frequency: 1)>
array([1490.], dtype=float32)
Coordinates:
  * frequency  (frequency) float32 30000.0
Attributes:
    long_name:      Indicative sound speed
    standard_name:  speed_of_sound_in_sea_water
    units:          m/s
    valid_min:      0.0

In [176]:
ds_test = xr.Dataset({'absorption_indicative': da_absorption_indicative,
                      'sound_speed_indicative': da_sound_speed_indicative}, 
                     coords={'frequency': (['frequency'], freq)})

In [183]:
ds_test.frequency.attrs['long_name'] = "Acoustic frequency"
ds_test.frequency.attrs['standard_name'] = "sound_frequency"
ds_test.frequency.attrs['units'] = "Hz"
ds_test.frequency.attrs['valid_min'] = 0.0

In [185]:
ds_test

<xarray.Dataset>
Dimensions:                 (frequency: 1)
Coordinates:
  * frequency               (frequency) float32 30000.0
Data variables:
    absorption_indicative   (frequency) float32 0.006
    sound_speed_indicative  (frequency) float32 1490.0

In [186]:
ds_test.frequency

<xarray.DataArray 'frequency' (frequency: 1)>
array([30000.], dtype=float32)
Coordinates:
  * frequency  (frequency) float32 30000.0
Attributes:
    long_name:      Acoustic frequency
    standard_name:  sound_frequency
    units:          Hz
    valid_min:      0.0

In [197]:
dsf = ds.to_netcdf(path='./test_assert2.nc')

In [199]:
ds.equals(xr.open_dataset('./test_assert2.nc'))

True

In [184]:
ds_env

<xarray.Dataset>
Dimensions:                 (frequency: 1)
Coordinates:
  * frequency               (frequency) float32 30000.0
Data variables:
    absorption_indicative   (frequency) float32 0.006
    sound_speed_indicative  (frequency) float32 1490.0

In [187]:
ds_env.frequency

<xarray.DataArray 'frequency' (frequency: 1)>
array([30000.], dtype=float32)
Coordinates:
  * frequency  (frequency) float32 30000.0
Attributes:
    long_name:      Acoustic frequency
    standard_name:  sound_frequency
    units:          Hz
    valid_min:      0.0

In [ ]:
ds = xr.Dataset({'d_all': data_d_all,
                     'h_actual_all': data_h_actual_all, 'h_est_all': data_h_est_all,
                     'beam_ij_all': data_beam_ij_all,
                     'hit_value_all': data_hit_value_all, 'hit_type_all': data_hit_type_all})

In [20]:
ds_sonar_beamgrp1 = xr.open_dataset(os.path.join(pname,fname),group='Sonar/Beam_group1', decode_times=False)

In [21]:
ds_sonar_beamgrp1

<xarray.Dataset>
Dimensions:                       (beam: 64, ping_time: 31)
Coordinates:
  * beam                          (beam) object '' '' '' '' '' '' '' '' '' ...
  * ping_time                     (ping_time) uint64 131545578247927373 ...
Data variables:
    backscatter_i                 (ping_time, beam) float32 ...
    backscatter_r                 (ping_time, beam) float32 ...
    beam_direction_x              (ping_time, beam) float32 ...
    beam_direction_y              (ping_time, beam) float32 ...
    beam_direction_z              (ping_time, beam) float32 ...
    beam_stabilisation            (ping_time) uint8 ...
    beam_type                     (ping_time) uint8 ...
    beamwidth_receive_major       (ping_time, beam) float32 ...
    beamwidth_receive_minor       (ping_time, beam) float32 ...
    beamwidth_transmit_major      (ping_time, beam) float32 ...
    beamwidth_transmit_minor      (ping_time, beam) float32 ...
    equivalent_beam_angle         (ping_time, beam)

In [25]:
ds_sonar_beamgrp1.backscatter_i

<xarray.DataArray 'backscatter_i' (ping_time: 31, beam: 64)>
array([[array([ 9.306826e-04, -9.643295e-04,  9.740553e-04, ..., -2.176321e-08,
        4.959619e-08, -6.815596e-08], dtype=float32),
        array([ 2.367373e-03, -2.931082e-03,  3.492698e-03, ..., -1.580587e-07,
        1.560583e-07, -1.411914e-07], dtype=float32),
        array([ 2.763227e-03, -3.198841e-03,  3.603501e-03, ..., -1.511683e-07,
        1.097476e-07, -6.187733e-08], dtype=float32),
        ...,
        array([-8.247152e-04,  9.756034e-04, -1.108371e-03, ..., -2.212049e-07,
        1.733083e-07, -1.273344e-07], dtype=float32),
        array([-6.019144e-04,  7.145707e-04, -8.055025e-04, ..., -6.644943e-08,
        4.060903e-08, -1.973221e-08], dtype=float32),
        array([ 5.815502e-04, -3.676428e-04,  1.077075e-04, ...,  7.978933e-08,
       -7.263365e-08,  6.334842e-08], dtype=float32)],
       [array([-3.267172e-03,  3.451781e-03, -3.538496e-03, ..., -4.994402e-08,
        5.128604e-08, -5.983535e-08], dty

In [24]:
ds_sonar_beamgrp1.beam_direction_x

<xarray.DataArray 'beam_direction_x' (ping_time: 31, beam: 64)>
array([[-0.815986, -0.849672, -0.875175, ..., -0.669452, -0.72544 , -0.774442],
       [-0.809192, -0.842597, -0.867887, ..., -0.663877, -0.7194  , -0.767994],
       [-0.809192, -0.842597, -0.867887, ..., -0.663877, -0.7194  , -0.767994],
       ...,
       [-0.796055, -0.828918, -0.853798, ..., -0.6531  , -0.707721, -0.755526],
       [-0.796055, -0.828918, -0.853798, ..., -0.6531  , -0.707721, -0.755526],
       [-0.796055, -0.828918, -0.853798, ..., -0.6531  , -0.707721, -0.755526]],
      dtype=float32)
Coordinates:
  * beam       (beam) object '' '' '' '' '' '' '' '' '' '' '' '' '' '' '' '' ...
  * ping_time  (ping_time) uint64 131545578247927373 131545578272146253 ...
Attributes:
    long_name:    x-component of the vector that gives the pointing direction...
    units:        1
    valid_range:  -1.0,1.0

In [35]:
import datetime as dt

In [39]:
time_obj = dt.datetime(2018,9,15,13,19,20)

In [47]:
time_obj.tzinfo

In [42]:
dt.tzinfo(time_obj)

In [60]:
dt.datetime(2018,9,15,13,19,20).isoformat()+'Z'

'2018-09-15T13:19:20Z'

In [59]:
dt.datetime.utcnow()

datetime.datetime(2018, 9, 15, 20, 29, 59, 592539)

In [53]:
dt.timezone.tzname()

TypeError: descriptor 'tzname' of 'datetime.timezone' object needs an argument

In [92]:
# Attributes
attrs_dict = dict()
attrs_dict['Conventions'] = "CF-1.7, SONAR-netCDF4, ACDD-1.3"
attrs_dict['date_created'] = dt.datetime(2018,9,15,13,19,20).isoformat()+'Z'
attrs_dict['keywords'] = "EK60"
attrs_dict['sonar_convention_authority'] = "ICES"
attrs_dict['sonar_convention_name'] = "SONAR-netCDF4"
attrs_dict['sonar_convention_version'] = "1.7"
attrs_dict['summary'] = "some test data"
attrs_dict['title'] = "Files generated by the XYZ sonar"

In [93]:
attrs_dict

{'Conventions': 'CF-1.7, SONAR-netCDF4, ACDD-1.3',
 'date_created': '2018-09-15T13:19:20Z',
 'keywords': 'EK60',
 'sonar_convention_authority': 'ICES',
 'sonar_convention_name': 'SONAR-netCDF4',
 'sonar_convention_version': '1.7',
 'summary': 'some test data',
 'title': 'Files generated by the XYZ sonar'}

In [76]:
# Open up .nc file for writing
ncfile2 = netCDF4.Dataset("./test2.nc", "w", format="NETCDF4")

In [77]:
[ncfile2.setncattr(k, v) for k, v in attrs_dict.items()]

[None, None, None, None, None, None, None]

In [78]:
ncfile2

<class 'netCDF4._netCDF4.Dataset'>
root group (NETCDF4 data model, file format HDF5):
    Conventions: CF-1.7, SONAR-netCDF4, ACDD-1.3
    date_created: 2018-09-15T13:19:20Z
    keywords: EK60
    sonar_convention_authority: ICES
    sonar_convention_name: SONAR-netCDF4
    sonar_convention_version: 1.7
    summary: some test data
    dimensions(sizes): 
    variables(dimensions): 
    groups: 

In [79]:
ncfile2.setncattr('test_key', 'test_value')

In [82]:
a = ncfile2.setncattr('test_key2', 'test_value2')
a

In [81]:
print(ncfile2.setncattr('test_key2', 'test_value2'))

None


In [89]:
try:
    [ncfile2.setncattr(k, v) for k, v in attrs_dict.items()]
    print('success')
except:
    print('otherwise')

success


In [91]:
with netCDF4.Dataset("./test3.nc", "w", format="NETCDF4") as ncfile3:
    [ncfile3.setncattr(k, v) for k, v in attrs_dict.items()]

In [69]:
for kv in attrs_dict.items():
    ncfile.setncattr(kk,vv)

('Conventions', 'CF-1.7, SONAR-netCDF4, ACDD-1.3')
('date_created', '2018-09-15T13:19:20Z')
('keywords', 'EK60')
('sonar_convention_authority', 'ICES')
('sonar_convention_name', 'SONAR-netCDF4')
('sonar_convention_version', '1.7')
('summary', 'some test data')


In [ ]:
# Attributes
ncfile.Conventions = "CF-1.7, SONAR-netCDF4, ACDD-1.3"
ncfile.date_created = date_created
ncfile.keywords = "EK60"
ncfile.sonar_convention_authority = "ICES"
ncfile.sonar_convention_name = "SONAR-netCDF4"
ncfile.sonar_convention_version = "1.7"
ncfile.summary = "some test data"

In [64]:
pwd

'/Users/wu-jung/code_git/echopype'